<?php
/**
 * @var $block KallieExperiments\AdvTemplateHints\Block\Html\Banner
 */
// todo create i18n
?>
<?php if ($block->displayAthBanner()) : ?>
    <div class="message global ath-banner">
        <div class="banner-toolbar">
            <div class="ath-xml-info"><?= $block->escapeHtml(__('Advanced Template Hints XML Viewer')) ?></div>
            <div class="ath-xml-button">
                <!--<button type="button" class="action button-banner"><span data-bind="i18n: 'View Banner'"></span></button>-->
                <?php if ($block->displayAthBannerInfo()) : ?>
                    <button type="button" class="action button-xml" id="ath-draggable-button" data-trigger="view-xml"><span data-bind="i18n: 'View XML'"></span></button>
                <?php endif ?>
            </div>
        </div>
    </div>
    <?php if ($block->displayAthBannerInfo()) : ?>
    <div id="ath-banner-modal" data-bind="mageInit: {
            'Magento_Ui/js/modal/modal':{
                'type': 'popup',
                'title': 'Advanced Template Hints XML Viewer',
                'trigger': '[data-trigger=view-xml]',
                'responsive': true,
                'buttons': [{
                    text: jQuery.mage.__('Close'),
                    class: 'action'
                }]
            }}">
        <div class="content">
            <div class="product data items" data-bind="mageInit: {
                'mage/tabs':{
                    'active': 0,
                    'trigger': '[data-toggle=trigger]',
                    'openedState': 'active'
                }}">
                <div class="item title" data-role="collapsible" role="tab">
                    <a class="switch" data-toggle="trigger" href="#tab-raw">Raw</a>
                </div>
                <div id="tab-raw" class="item content" data-role="content" role="tabpanel"><div class='inner-content xml-string'><?= $block->getLayoutXmlString() ?></div></div>

                <!--
                <div class="item title" data-role="collapsible" role="tab">
                    <a class="switch" data-toggle="trigger" href="#tab-generated">Generated</a>
                </div>
                <div id="tab-generated" class="item content" data-role="content" role="tabpanel"><div class="inner-content">Content coming soon...</div></div>
                -->

                <div class="item title" data-role="collapsible" role="tab">
                    <a class="switch" data-toggle="trigger" href="#tab-handles">Layout Handles</a>
                </div>
                <div id="tab-handles" class="item content" data-role="content" role="tabpanel"><div class="inner-content"><?= $block->getLayoutHandles() ?></div></div>

                <!--
                <div class="item title" data-role="collapsible" role="tab">
                    <a class="switch" data-toggle="trigger" href="#tab-template-data">Template Data</a>
                </div>
                <div id="tab-template-data" class="item content" data-role="content" role="tabpanel"><div class="inner-content"><?/*= $block->getTemplateData() */?></div></div>
                -->
            </div>
        </div>
    </div>
    <?php endif; ?>
    <!-- todo get draggable to work <script>
        require(['jquery', 'draggable'], function($) {
            $(function () {
                $( "#ath-draggable-button" ).draggable();
            });
        });
    </script>-->
<?php endif; ?>
